"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.x.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""


from datetime import timedelta
from pathlib import Path
from django.contrib.messages import constants as messages
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="test")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool, default=True)
SHOW_DEBUGGER_TOOLBAR = config(
    "SHOW_DEBUGGER_TOOLBAR", cast=bool, default=False)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    cast=lambda v: [s.strip() for s in v.split(",")],
    default="*",
)

COMINGSOON = config("COMINGSOON", cast=bool, default=False)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "django.contrib.humanize",
    "imagekit",
    "ckeditor",
    "ckeditor_uploader",

    "meta",
    "compressor",
    # "robots.apps.RobotsConfig",  
    # "robots_txt",  
    "aio_offline_captcha",
    'aio_analytics',
    'honeypot',    

    "website",
    "accounts",
    "library",
    "dashboard",
    "filehub",

    "DogWalker",
    "DogOwner",
   
    
]


SITE_ID = config("SITE_ID", cast=int, default=1)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.context"
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


DATABASES = {
    # "default": {
    #     "ENGINE": config("PGDB_ENGINE", default="django.db.backends.postgresql"),
    #     "NAME": config("PGDB_NAME", default="postgres"),
    #     "USER": config("PGDB_USER", default="postgres"),
    #     "PASSWORD": config("PGDB_PASS", default="postgres"),
    #     "HOST": config("PGDB_HOST", default="db"),
    #     "PORT": config("PGDB_PORT", cast=int, default=5432),
    # }
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = config("TIME_ZONE", default="UTC")

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images) and media files
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
MEDIA_URL = "/media/"

STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / "media"


STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# messages configuration for notification handeling in pages
MESSAGE_TAGS = {
    messages.DEBUG: "info",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "error",
}


# Compress Configs
COMPRESS_ENABLED = config("COMPRESS_ENABLED", cast=bool, default=False)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # other finders..
    'compressor.finders.CompressorFinder',
)


# COMPRESS_REBUILD_TIMEOUT= 86400
COMPRESS_OFFLINE = config("COMPRESS_OFFLINE", cast=bool, default=False)
COMPRESS_CSS_FILTERS = [
    'compressor.filters.cssmin.CSSMinFilter'
]
COMPRESS_JS_FILTERS = [
    'compressor.filters.jsmin.JSMinFilter'
]
if config("COMPRESS_GZIP_ENABLED", cast=bool, default=False):
    COMPRESS_STORAGE = 'compressor.storage.GzipCompressorFileStorage'

# Email Configurations for production and development

EMAIL_BACKEND = config(
    "EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = config("EMAIL_HOST", default="smtp4dev")
EMAIL_PORT = config("EMAIL_PORT",cast=int, default=25)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_SSL = config("EMAIL_USE_SSL", cast=bool, default=True)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool, default=False)
DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL", default="from@example.com")


# security configs for production
if config("USE_SSL_CONFIG", cast=bool, default=False):
    # cookie secure settings
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_NAME = 'prefix_sessionid'
    
    # csrf secure settings
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_NAME = 'prefix_csrftoken'
    

    # HSTS settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    # more security settings
    SECURE_SSL_REDIRECT = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "SAMEORIGIN"
    SECURE_REFERRER_POLICY = "strict-origin"
    USE_X_FORWARDED_HOST = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# django debug toolbar for docker usage
if SHOW_DEBUGGER_TOOLBAR:
    INSTALLED_APPS += [
        "debug_toolbar",
    ]
    MIDDLEWARE += [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    ]
    import socket  # only if you haven't already imported this
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS = [
        ip[: ip.rfind(".")] + ".1" for ip in ips] + ["127.0.0.1", "10.0.2.2"]



# production whitenoise
if config("ENABLE_WHITENOISE", cast=bool, default=False):
    # Insert Whitenoise Middleware.
    MIDDLEWARE += [
        "whitenoise.middleware.WhiteNoiseMiddleware",
    ]
    STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'

    # Enable GZip.
    # STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# meta configurations
META_SITE_PROTOCOL = 'https'
META_SITE_DOMAIN = 'hopgo.ir'
META_SITE_TYPE = "website"
META_USE_SITES = True
META_DEFAULT_IMAGE = "/static/images/alibigdeli.png"
META_DEFAULT_KEYWORDS = ['dog', 'pet', 'dogwalker', 'dogownewr',
                         'سگ', 'پت', 'داگ واکر', 'داگ اونر']
META_INCLUDE_KEYWORDS = ['dog', 'pet', 'dogwalker', 'dogownewr',
                         'سگ', 'پت', 'داگ واکر', 'داگ اونر']
META_USE_OG_PROPERTIES = True
META_USE_SCHEMAORG_PROPERTIES = True
META_USE_TITLE_TAG = True
META_SCHEMAORG_TYPE = "Website"
META_SITE_NAME = "HopGo"


# robots.txt configuration
ROBOTS_USE_SITEMAP = True
ROBOTS_USE_HOST = True

# ckeditor configuration
CKEDITOR_UPLOAD_PATH = 'ckeditor_uploads'
CKEDITOR_RESTRICT_BY_DATE = False
SILENCED_SYSTEM_CHECKS = ["ckeditor.W001"]

CKEDITOR_CONFIGS = {
    'default': {
        'width': '100%',
        'toolbar': 'full',
        'extraPlugins': ','.join([
            'uploadimage',  # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            'image',
            # 'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath',
            'codesnippet'

        ]),
        'allowedContent':True,
        "iframe_attributes": {
            'sandbox': 'allow-scripts allow-same-origin allow-presentation',
            'allow': 'autoplay'
        }
    },

}



# Custom User Management
AUTH_USER_MODEL = "accounts.User"
AUTH_PROFILE_MODULE = "accounts.User"
LOGOUT_REDIRECT_URL = "/"
LOGIN_REDIRECT_URL = '/'
ENABLE_ACCOUNTS_PAGES = True
ENABLE_ACCOUNTS_API = False

# recaptcha configs
OFFLINE_CAPTCHA_ADMIN_ENABLE =  config("OFFLINE_CAPTCHA_ADMIN_ENABLE",cast=bool, default=True)


# honeypot configs
HONEYPOT_LOGIN_TRYOUT = config("HONEYPOT_LOGIN_TRYOUT",cast=int, default=5)


# caching system
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}


GTAG_TOKEN_ID = config("GTAG_TOKEN_ID", default="G-XXXXXXXXX")




# sentry online monitoring
SENTRY_ENABLE = config("SENTRY_ENABLE", cast=bool, default=False)
if SENTRY_ENABLE == True:
    SENTRY_DNS = config("SENTRY_DNS")
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DNS,
        integrations=[
            DjangoIntegration(),
        ],
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for performance monitoring.
        # We recommend adjusting this value in production.
        traces_sample_rate=1.0,
        # If you wish to associate users to errors (assuming you are using
        # django.contrib.auth) you may enable sending PII data.
        send_default_pii=True,
    )
    


DISABLE_CACHE = config("DISABLE_CACHE",cast=bool, default=True)