# Generated by Django 5.2 on 2026-08-10 15:40

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(max_length=20, unique=True, validators=[accounts.validators.validate_iranian_national_id], verbose_name='کد ملی'),
        ),
    ]
