# Generated by Django 5.2 on 2026-08-17 10:10

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[accounts.validators.validate_iranian_national_id], verbose_name='کد ملی'),
        ),
    ]
