# Generated by Django 5.2 on 2026-08-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'داگ واکر'), (2, 'داگ اونر'), (10, 'ادمین')], default=1),
        ),
    ]
