# Generated by Django 5.2 on 2026-08-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='test', max_length=255, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
