# Generated by Django 5.2 on 2026-08-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'dog owner'), (2, 'dog walker'), (10, 'admin')], default=1),
        ),
    ]
