# Generated by Django 5.2 on 2026-08-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'walker'), (2, 'owner'), (10, 'admin')], default=2),
        ),
    ]
