# Generated by Django 5.2 on 2026-08-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'owner'), (2, 'walker'), (10, 'admin')], default=1),
        ),
    ]
